storage:
  type: SQLITE
  host: localhost
  port: 3306
  database: betterchestshops
  username: betterchestshops
  password: betterchestshops
  properties:
    useUnicode: true
    characterEncoding: utf8

hologram:
  handler: auto
  refresh:
    interval: 600
  offset:
    x: 0.5
    y: 1.0
    z: 0.5

debug: false

config-version: 1